### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [MarcDonald/Hibi#32]
Hi @MarcDonald 

Since this app is Apache v2 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by MarcDonald** [comment]
Hey, thanks for letting me know. I'll try and get it submitted to F-Droid soon. I'll update this ticket when I do.

**Comment by MarcDonald** [comment]
Commenting to say I haven't forgotten about this. Unfortunately my PC died so I haven't got a chance to work on it, I intend to submit it for inclusion with the next release whenever I get a new PC.

**Comment by Poussinou** [comment]
No problem, take your time 👍 
You can start the process by opening a [RFP](https://gitlab.com/fdroid/rfp/issues)

**Comment by MarcDonald** [comment]
Released [version 1.3](https://github.com/MarcDonald/Hibi/releases/tag/v1.3.2%3B34) and opened an [RFP](https://gitlab.com/fdroid/rfp/issues/1174)
