### ISSUE TITLE
[BUG] backup not work

### ISSUE THREAD

**Issue by Zebra67** [MarcDonald/Hibi#38]
when I click backup it crashes
![Uploading IMG_20200503_094321.jpg…]()

see pic I got this error every time.

**Comment by MarcDonald** [comment]
Hey, thanks for reporting this. It seems like the the link to your image is broken so I can't click it.

Would you be able to let me know some more information so I can try and debug this?

- What phone and what version of Android are you running this on?
- How many entries do you have?
- How many photos do you have attached to entries?

**Comment by Zebra67** [comment]
I Have Redmi note 7 pro
ver-9
I have 3-4 entries 
0 photos attached

**Comment by tigerninjas** [comment]
still no update?

**Comment by Zebra67** [comment]
no update?

**Comment by MarcDonald** [comment]
I think I have identified the issue, for testing purposes would you be able to try attaching an image to an entry and then attempting to backup. If that works, I should have a fix out soon.

**Comment by Zebra67** [comment]
If one entry I added and try to backup it crashes
If one entry with image I added and try to backup it show success but while click on Restore it show empty  see attched screenshots
![Screenshot_2020-05-17-07-38-29-1
![Screenshot_2020-05-17-07-37-10-382_com marcdonald hibi](https://user-images.githubusercontent.com/41435599/82134114-b5316280-9811-11ea-9055-8ea5e995a5d3.jpg)
06_com marcdonald hibi](https://user-images.githubusercontent.com/41435599/82134112-b3679f00-9811-11ea-9886-1fb6115f0246.jpg)
![Screenshot_2020-05-17-07-37-54-486_com marcdonald hibi](https://user-images.githubusercontent.com/41435599/82134113-b498cc00-9811-11ea-9125-47a43b0c695a.jpg)


![Screenshot_2020-05-17-07-38-35-229_com marcdonald hibi](https://user-images.githubusercontent.com/41435599/82134110-b19ddb80-9811-11ea-8142-40666b9ffc53.jpg)

**Comment by MarcDonald** [comment]
In order to restore from a backup you need to click the share button and save it using a file explorer app such as Solid Explorer. I'll add some text to the dialog to explain that as it's not very clear currently. I'm also working on a way to save it onto the device properly so that this step isn't needed at all. Thanks for your help with this 🙂.
